services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
